project/codemark/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('logout/', views.logout_view, name='logout'),
    path('enroll/', views.enroll_view, name='enroll'),
    path('unenroll/<slug:class_pk>/', views.unenroll_view, name='unenroll'),
    path('class/<slug:class_pk>/', views.class_view, name='class'),
    path('grades/<slug:class_pk>/', views.grades_view, name='grades'),
    path('download_grades/<slug:class_pk>/<slug:assignment_pk>/', views.download_grades_view, name='download_grades'),
    path('class_assignments_update/<slug:pk>/', views.ClassAssignmentsUpdateView.as_view(), name='class_assignments_update'),
    path('assignment/create/', views.AssignmentCreateView.as_view(), name='assignment_create'),
    path('assignment/update/<slug:pk>/', views.AssignmentUpdateView.as_view(), name='assignment_update'),
    path('assignment/delete/<slug:pk>/', views.AssignmentDeleteView.as_view(), name='assignment_delete'),
    path('fixture/create/', views.FixtureCreateView.as_view(), name='fixture_create'),
    path('fixture/update/<slug:pk>/', views.FixtureUpdateView.as_view(), name='fixture_update'),
    path('fixture/delete/<slug:pk>/', views.FixtureDeleteView.as_view(), name='fixture_delete'),
    path('file/create/', views.FileCreateView.as_view(), name='file_create'),
    path('file/update/<slug:pk>/', views.FileUpdateView.as_view(), name='file_update'),
    path('file/delete/<slug:pk>/', views.FileDeleteView.as_view(), name='file_delete'),
    path('level/create/', views.LevelCreateView.as_view(), name='level_create'),
    path('level/update/<slug:pk>/', views.LevelUpdateView.as_view(), name='level_update'),
    path('level/delete/<slug:pk>/', views.LevelDeleteView.as_view(), name='level_delete'),
    path('step/select/', views.StepSelectView.as_view(), name='step_select'),
    path('step/update/<slug:pk>/', views.StepUpdateView.as_view(), name='step_update'),
    path('run_step/create/', views.RunStepCreateView.as_view(), name='run_step_create'),
    path('run_step/update/<slug:pk>/', views.RunStepUpdateView.as_view(), name='run_step_update'),
    path('run_step/delete/<slug:pk>/', views.RunStepDeleteView.as_view(), name='run_step_delete'),
    path('test_step/create/', views.TestStepCreateView.as_view(), name='test_step_create'),
    path('test_step/update/<slug:pk>/', views.TestStepUpdateView.as_view(), name='test_step_update'),
    path('test_step/delete/<slug:pk>/', views.TestStepDeleteView.as_view(), name='test_step_delete'),
    path('file_schema/create/', views.FileSchemaCreateView.as_view(), name='file_schema_create'),
    path('file_schema/update/<slug:pk>/', views.FileSchemaUpdateView.as_view(), name='file_schema_update'),
    path('file_schema/delete/<slug:pk>/', views.FileSchemaDeleteView.as_view(), name='file_schema_delete'),
    path('text/create/', views.TextCreateView.as_view(), name='text_create'),
    path('text/update/<slug:pk>/', views.TextUpdateView.as_view(), name='text_update'),
    path('text/delete/<slug:pk>/', views.TextDeleteView.as_view(), name='text_delete'),
    path('submit/<slug:class_pk>/<slug:assignment_pk>/', views.submit_view, name='submit'),
    path('submission/<slug:submission_pk>/', views.submission_view, name='submission'),
    path('run_submission/<slug:submission_pk>/', views.run_submission_view, name='run_submission'),
    path('run_assignment/<slug:class_pk>/<slug:assignment_pk>/', views.run_assignment_view, name='run_assignment'),
    path('plagiarism/<slug:class_pk>/<slug:assignment_pk>/', views.plagiarism_view, name='plagiarism'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='password_reset/request.html', subject_template_name='password_reset/subject.txt', html_email_template_name='password_reset/email.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset/done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/complete.html'), name='password_reset_complete'),
    path('', views.index_view, name='index'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('verification/', include('verify_email.urls')),
    path('', include('codemark.urls')),
]

project/codemark/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import AbstractUser, PermissionsMixin, Group
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator, MaxValueValidator
from polymorphic.models import PolymorphicModel
from datetime import timedelta, datetime
import os
import shutil


GCC = 'gcc'
PYTHON = 'python'
ALPINE = 'alpine'
UBUNTU = 'ubuntu'
BASH = 'bash'
RUST = 'rust'
JAVA = 'java'
NODE = 'node'
CONTAINER_CHOICES = [
    (GCC, 'GCC'),
    (PYTHON, 'Python'),
    (ALPINE, 'Alpine'),
    (UBUNTU, 'Ubuntu'),
    (BASH, 'Bash'),
    (RUST, 'Rust'),
    (JAVA, 'Java'),
    (NODE, 'Node'),
]


class User(AbstractUser):
    email = models.EmailField(blank=False, unique=True)
    nickname = models.CharField(blank=True, null=True, max_length=30)
    phone_number = PhoneNumberField(blank=True, null=True)
    school_id = models.CharField(
        blank=False, null=True, max_length=30, verbose_name='School ID'
    )

    @property
    def is_instructor(self):
        return Class.objects.filter(instructors=self).count() > 0


class Department(models.Model):
    name = models.CharField(max_length=30)
    abbreviation = models.CharField(max_length=4)

    def __str__(self):
        return self.name


def user_directory_path(instance, filename):
    return 'user/{0}/{1}/{2}'.format(instance.creator.id, datetime.now().strftime('%Y-%m-%d--%H-%M-%S'), filename)


class File(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.FileField(upload_to=user_directory_path)

    def copy(self, dest, name=None):
        if not name:
          name = self.file.name
        dst = open(os.path.join(dest, os.path.basename(name)), "wb")
        shutil.copyfileobj(self.file, dst)

    def __str__(self):
        return os.path.basename(self.file.name)


class Fixture(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    files = models.ManyToManyField(File)

    def __str__(self):
        return self.name


class Text(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text


class FileSchema(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    files = models.ManyToManyField(Text)

    def __str__(self):
        return self.name

    @property
    def file_names(self):
        return ', '.join([str(file) for file in self.files.all()])


class Step(PolymorphicModel):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    number = models.IntegerField(
        default=1, validators=[MinValueValidator(1)]
    )
    weight = models.IntegerField(
        default=0, validators=[MinValueValidator(0)]
    )
    hidden = models.BooleanField()

    def __str__(self):
        return self.name + ' - ' + str(self.number)

    class Meta:
        ordering = ['number']


class RunStep(Step):
    command = models.TextField()
    timeout = models.DurationField()

    def __str__(self):
        return self.command + ' - ' + str(self.number)


class TestStep(Step):
    command = models.TextField()
    timeout = models.DurationField()
    expected_output = models.TextField()
    case_insensitive = models.BooleanField()
    strip_whitespace = models.BooleanField()

    def __str__(self):
        return self.command + ' - ' + str(self.number)


class Level(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    steps = models.ManyToManyField(Step)

    container = models.CharField(
        max_length=30,
        choices=CONTAINER_CHOICES,
        default=GCC,
    )

    def __str__(self):
        return self.name


class Assignment(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    deadline = models.DateTimeField(blank=True, null=True)
    late_deadline = models.DateTimeField(blank=True, null=True)
    submission_limit = models.IntegerField(
        default=0, validators=[MinValueValidator(0)]
    )
    cool_off = models.DurationField(default=timedelta())
    fixture = models.ForeignKey(
        Fixture, on_delete=models.PROTECT, blank=True, null=True
    )
    levels = models.ManyToManyField(Level, blank=True)
    submission_files = models.ForeignKey(
        FileSchema, on_delete=models.PROTECT, blank=True, null=True
    )

    def __str__(self):
        return self.name

    def submittable(self, user):
        query = Submission.objects.filter(
            submitter=user).filter(assignment=self)
        if self.submission_limit and query.count() > self.submission_limit:
            return False
        elif query.count() > 0 and timezone.now() - query.latest().timestamp < self.cool_off:
            return False
        elif self.late_deadline:
            return timezone.now() < self.late_deadline
        elif self.deadline:
            return timezone.now() < self.deadline
        else:
            return True

    @property
    def total_points(self):
        points = 0
        for level in self.levels.all():
            for step in level.steps.all():
                points += step.weight
        return points

    @property
    def past_due(self):
        if self.deadline:
            return timezone.now() > self.deadline
        else:
            return False

    @property
    def past_late_due(self):
        if self.late_deadline:
            return timezone.now() > self.late_deadline
        else:
            return False

    @property
    def due_delta(self):
        if self.deadline:
            return self.deadline - timezone.now()
        else:
            return None

    @property
    def late_due_delta(self):
        if self.late_deadline:
            return self.late_deadline - timezone.now()
        else:
            return None


class Course(models.Model):
    name = models.CharField(max_length=30)
    number = models.CharField(max_length=4)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.department.abbreviation + ' ' + self.number


class Class(models.Model):
    class Term(models.TextChoices):
        FALL = 'FA', _('Fall')
        WINTER = 'WI', _('Winter')
        SPRING = 'SP', _('Spring')
        SUMMER = 'SU', _('Summer')
    term = models.CharField(
        max_length=2,
        choices=Term.choices
    )
    year = models.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2100)]
    )
    section = models.CharField(max_length=4)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    instructors = models.ManyToManyField(User, related_name='instructor_users')
    students = models.ManyToManyField(User, related_name='student_users')
    assignments = models.ManyToManyField(Assignment)

    def __str__(self):
        return str(self.course) + '.' + self.section + ' ' + self.get_term_display() + ' ' + str(self.year) + ' - ' + ', '.join([instructor.get_full_name() for instructor in self.instructors.all()])

    class Meta:
        verbose_name_plural = 'Classes'


class Submission(models.Model):
    submitter = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    enrolled_class = models.ForeignKey(Class, on_delete=models.CASCADE)
    files = models.ManyToManyField(File)

    def __str__(self):
        return self.assignment.name + ' ' + self.submitter.get_full_name() + ' - ' + str(self.timestamp)

    @property
    def latest_result(self):
        query = Result.objects.filter(submission=self)
        result = None
        if query.count() > 0:
            result = query.latest()
        return result

    class Meta:
        ordering = ['-timestamp']
        get_latest_by = ['timestamp']


class StepOutput(PolymorphicModel):
    name = models.CharField(max_length=30)
    number = models.IntegerField(
        default=1, validators=[MinValueValidator(1)]
    )
    weight = models.IntegerField(
        default=0, validators=[MinValueValidator(0)]
    )
    hidden = models.BooleanField()

    def __str__(self):
        return self.name + ' - ' + str(self.number)

    @property
    def grade(self):
        return 0

    class Meta:
        ordering = ['number']


class RunStepOutput(StepOutput):
    command = models.TextField()
    timeout = models.DurationField()
    stdout = models.TextField(null=True)
    stderr = models.TextField(null=True)
    timed_out = models.BooleanField(null=True)

    def __str__(self):
        return self.command + ' - ' + str(self.number)

    @property
    def grade(self):
        return self.weight if not self.stderr else 0


class TestStepOutput(StepOutput):
    command = models.TextField()
    timeout = models.DurationField()
    expected_output = models.TextField()
    case_insensitive = models.BooleanField()
    strip_whitespace = models.BooleanField()
    actual_output = models.TextField(null=True)
    timed_out = models.BooleanField(null=True)

    def __str__(self):
        return self.command + ' - ' + str(self.number)

    @property
    def grade(self):
        expected = str(self.expected_output)
        actual = str(self.actual_output)
        if self.case_insensitive:
            expected = expected.lower()
            actual = actual.lower()
        if self.strip_whitespace:
            expected = expected.strip()
            actual = actual.strip()
        return self.weight if expected == actual else 0


class LevelOutput(models.Model):
    name = models.CharField(max_length=30)

project/codemark/templates/codemark/base.html
{% extends "base.html" %}
{% load static %}
{% block header %}
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{% url 'index' %}" style="color: inherit;">
      <img src="{% static "favicon/icon.png" %}">
      &nbsp;{{ request.user.get_full_name }}
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navigation">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navigation" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="{% url 'index' %}">
        Home
      </a>
      <a class="navbar-item" href="{% url 'profile' %}">
        Profile
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <a class="button is-light is-expanded is-fullwidth" href="{% url 'logout' %}">
          Logout
        </a>
      </div>
    </div>
  </div>
</nav>

<script>
  document.addEventListener('DOMContentLoaded', () => {

    // Get all "navbar-burger" elements
    const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

    // Check if there are any navbar burgers
    if ($navbarBurgers.length > 0) {

      // Add a click event on each of them
      $navbarBurgers.forEach(el => {
        el.addEventListener('click', () => {

          // Get the target from the "data-target" attribute
          const target = el.dataset.target;
          const $target = document.getElementById(target);

          // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
          el.classList.toggle('is-active');
          $target.classList.toggle('is-active');

        });
      });
    }
  });
</script>
{% endblock %}

project/codemark/templates/codemark/class.html
{% extends "codemark/base.html" %}
{% load filter %}
{% block title %} {{ class }} {% endblock %}
{% block content %}
<section class="section">
  <div class="container">
    <div class="columns is-multiline is-centered">
      <div class="column is-three-quarters has-text-centered">
        <h3 class="title has-text-centered">{{ class }}</h3>
      </div>
    </div>
    <div class="columns is-multiline is-centered">
      <div class="column box is-three-quarters">
        <div class="table-container">
          <table class="table is-fullwidth is-narrow">
            <thead>
              <tr class="is-selected">
                <th class="is-vcentered">Submit</th>
                <th class="is-vcentered">Assignment</th>
                <th class="is-vcentered">Due Deadline</th>
                <th class="is-vcentered">Late Due Deadline</th>
                <th class="is-vcentered">Required Files</th>
                <th class="is-vcentered">Submissions</th>
              </tr>
            </thead>
            <tbody>
              {% for assignment in class.assignments.all %}
              <tr>
                <th class="is-vcentered">
                  {% if assignment|submittable:request.user %}
                  <a class="button is-small is-link is-inverted"
                    href="{% url 'submit' class_pk=class.pk assignment_pk=assignment.pk%}">Submit
                    Assignment
                  </a>
                  {% else %}
                  <a class="button is-small is-link is-inverted" disabled>
                    Submit Assignment
                  </a>
                  {% endif %}
                </th>
                <th class="is-vcentered">{{ assignment.name }}</th>
                <th class="is-vcentered">{{ assignment.deadline|date:'m/d-h:iA' }}
                  {% if not assignment.past_due %}
                  ({{ assignment.due_delta|smooth_timedelta }})
                  {% endif %}
                </th>
                <th class="is-vcentered">{{ assignment.late_deadline|date:'m/d-h:iA' }}
                  {% if not assignment.past_late_due %}
                  ({{ assignment.late_due_delta|smooth_timedelta }})
                  {% endif %}
                </th>
                <th class="is-vcentered">
                  {% for file in assignment.submission_files.files.all %}
                  {{ file }}&nbsp;
                  {% endfor %}
                </th>
                <th class="is-vcentered">
                  <div class="select is-primary">
                    <select
                      onchange="let index = this.selectedIndex; this.selectedIndex = -1; location = this.options[index].value;"
                      onfocus="this.selectedIndex = -1;">
                      {% for submission in assignment.submission_set.all|submitted_in:class|submitted_by:request.user %}
                      <option value="{% url 'submission' submission_pk=submission.pk %}">
                        {{ submission.timestamp|date:'m/d-h:iA' }}</option>
                      {% endfor %}
                    </select>
                  </div>
                </th>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      {% if request.user in class.instructors.all %}
      <div class="column box is-three-quarters">
        <div class="field is-grouped is-expanded is-fullwidth">
          <div class="control is-expanded">
            <a class="button is-primary is-fullwidth" href="{% url 'class_assignments_update' pk=class.pk %}">
              Edit Class
            </a>
          </div>
          <div class="control is-expanded">
            <a class="button is-info is-fullwidth" href="{% url 'grades' class_pk=class.pk %}">
              View Grades
            </a>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</section>
{% endblock %}

project/codemark/templates/codemark/grades.html
{% extends "codemark/base.html" %}
{% load filter %}
{% block title %} {{ class }} {% endblock %}
{% block content %}
<section class="section">
  <div class="container">
    <div class="columns is-multiline is-centered">
      <div class="column is-three-quarters has-text-centered">
        <h3 class="title has-text-centered">{{ class }}</h3>
      </div>
    </div>
    <div class="columns is-multiline is-centered">
      {% for assignment in class.assignments.all %}
      <div class="column box is-three-quarters has-text-centered">
        <div class="tags has-addons is-centered">
          <span class="tag">{{ assignment }}</span>
          <a href="{% url 'download_grades' class_pk=class.pk assignment_pk=assignment.pk %}" download
            class="tag is-link" style="white-space: pre-wrap;">Download CSV</a>
          <a href="{% url 'assignment_update' pk=assignment.pk %}" class="tag is-primary"
            style="white-space: pre-wrap;">Edit Assignment</a>
          <a href="{% url 'plagiarism' class_pk=class.pk assignment_pk=assignment.pk %}" class="tag is-warning"
            style="white-space: pre-wrap;">Check Plagiarism</a>
          <a href="{% url 'run_assignment' class_pk=class.pk assignment_pk=assignment.pk %}" class="tag is-danger"
            style="white-space: pre-wrap;">Rerun Submissions</a>

        </div>
        <div class="table-container">
          <table class="table is-fullwidth is-narrow">
            <thead>
              <tr class="is-selected">
                <th class="is-vcentered">Last Name</th>
                <th class="is-vcentered">First Name</th>
                <th class="is-vcentered">Username</th>
                <th class="is-vcentered">Student ID</th>
                <th class="is-vcentered">Last Access</th>
                <th class="is-vcentered">Grade [Total Pts: {{ assignment.total_points }}] </th>
                <th class="is-vcentered">Submissions</th>
              </tr>
            </thead>
            <tbody>
              {% for student in class.students.all %}
              <tr>
                <th class="is-vcentered">
                  {{ student.last_name }}
                </th>
                <th class="is-vcentered">
                  {{ student.first_name }}
                </th>
                <th class="is-vcentered">
                  {{ student.username }}
                </th>
                <th class="is-vcentered">
                  {{ student.school_id }}
                </th>
                <th class="is-vcentered">
                  {{ assignment.submission_set.all|submitted_in:class|submitted_by:student|latest|timestamp|date:'m/d-h:iA' }}
                </th>
                <th class="is-vcentered">
                  {{ assignment.submission_set.all|submitted_in:class|submitted_by:student|latest|grade }}
                </th>
                <th class="is-vcentered">
                  <div class="select is-primary">
                    <select
                      onchange="let index = this.selectedIndex; this.selectedIndex = -1; location = this.options[index].value;"
                      onfocus="this.selectedIndex = -1;">
                      {% for submission in assignment.submission_set.all|submitted_in:class|submitted_by:student %}
                      <option value="{% url 'submission' submission_pk=submission.pk %}">
                        {{ submission.timestamp|date:'m/d-h:iA' }}</option>
                      {% endfor %}
                    </select>
                  </div>
                </th>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>
</section>
{% endblock %}

project/codemark/templates/codemark/index.html
{% extends "codemark/base.html" %}
{% load widget_tweaks %}
{% block title %} CodeMark {% endblock %}
{% block content %}
<section class="section">
  <div class="container">
    <div class="columns is-centered is-multiline">
      <div class="column is-half has-text-centered">
        <h3 class="title has-text-centered">CodeMark</h3>
      </div>
    </div>
    {% if instructed_classes %}
    <div class="columns is-multiline is-centered m-3">
      <div class="column box is-half">
        <aside class="menu">
          <p class="menu-label">
            Instructed Classes
          </p>
          {% for class in instructed_classes %}
          <ul class="menu-list">
            <div class="field has-addons">
              <li class="control is-expanded"><a href="{% url 'class' class_pk=class.pk %}"><b>{{ class }}</b></a></li>
            </div>
          </ul>
          </ul>
          {% endfor %}
        </aside>
      </div>
    </div>
    {% endif %}
    {% if taken_classes %}
    <div class="columns is-multiline is-centered m-3">
      <div class="column box is-half">
        <aside class="menu">
          <p class="menu-label">
            Taken Classes
          </p>
          {% for class in taken_classes %}
          <ul class="menu-list">
            <div class="field has-addons">
              <li class="control is-expanded"><a href="{% url 'class' class_pk=class.pk %}"><b>{{ class }}</b></a></li>
              <a class="control button is-small is-danger is-inverted my-1 mx-0 is-right is-pulled-right"
                href="{% url 'unenroll' class_pk=class.pk %}">Unenroll</a>
            </div>
          </ul>
          </ul>
          {% endfor %}
        </aside>
      </div>
    </div>
    {% endif %}

    <div class="columns is-multiline is-centered m-3">
      <div class="column box is-half">
        <p class="menu-label">
          Enroll in Class
        </p>
        <form action="{% url 'enroll' %}" method="post">
          {% csrf_token %}
          {% for field in form %}
          <div class="field has-addons">
            {% if field.errors %}
            <div class="control is-expanded">
              {{ field|add_class:'input is-danger' }}
            </div>
            {% for error in field.errors %}
            <li class="help is-danger">{{ error }}</li>
            {% endfor %}
            {% else %}
            <div class="control is-expanded">
              {{ field|add_class:'input' }}
            </div>
            {% endif %}
          </div>
          {% endfor %}
          <div class="control">
            <input type="submit" class="button is-primary is-fullwidth" value="Enroll" />
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

project/codemark/templates/codemark/profile.html
{% extends "codemark/base.html" %}
{% load widget_tweaks %}
{% block title %} Profile {% endblock %}
{% block content %}
<section class="hero is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-multiline is-centered">
        <div class="column is-half has-text-centered">
          <h3 class="title has-text-centered">Profile</h3>
        </div>
      </div>
      <div class="columns is-multiline is-centered">
        <div class="column is-half">
          <div class="box">
            <form action="{% url 'profile' %}" method="post">
              {% csrf_token %}
              {% for field in form %}
              <div class="field">
                <label class="label">{{ field.label_tag }}</label>
                {% if field.errors %}
                <div class="control">
                  {{ field|add_class:'input is-danger' }}
                </div>
                {% for error in field.errors %}
                <p class="help is-danger">{{ error }}</p>
                {% endfor %}
                {% else %}
                <div class="control">
                  {{ field|add_class:'input' }}
                </div>
                {% endif %}
              </div>
              {% endfor %}
              <div class="field">
                <input type="submit" class="button is-primary is-fullwidth" value="Update" />
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
</section>
{% endblock %}

project/codemark/templates/codemark/submit.html
{% extends "codemark/base.html" %}
{% load widget_tweaks %}
{% block title %} Submit Assignment {% endblock %}
{% block content %}
<section class="section">
  <div class="container">
    <div class="columns is-centered is-multiline">
      <div class="column is-half has-text-centered">
        <h3 class="title has-text-centered">Submit</h3>
      </div>
    </div>
    <div class="columns is-centered is-multiline">
      <div class="column m-3 box is-half">
        {% if assignment.submission_files %}
        <form action="{% url 'submit' class_pk=class.pk assignment_pk=assignment.pk %}" method="post"
          enctype="multipart/form-data">
          {% csrf_token %}
          {{ formset.management_form }}
          {% for form in formset %}
          {% for field in form %}
          <div class="field">
            <label class="label">{{ field.label_tag }}</label>
            {% if field.errors %}
            <div class="control">
              {{ field|add_class:'input is-danger'|attr:'required' }}
            </div>
            {% for error in field.errors %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
            {% else %}
            <div class="control">
              {{ field|add_class:'input'|attr:'required' }}
            </div>
            {% endif %}
          </div>
          {% endfor %}
          {% endfor %}
          <div class="field">
            <div class="control">
              <input type="submit" class="button is-primary is-fullwidth" value="Submit" />
            </div>
          </div>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock %}